### ISSUE TITLE
Real time camera predict

### ISSUE THREAD

**Issue by hairymax** [hairymax/Face-AntiSpoofing#2]
Detecting Real and Fake faces on real time camera

**Comment by hairymax** [comment]
@danii92
I opened a new issue for this feature

Answer for your question
> do you have any idea how can i modify code to detect (real, fake) faces on real time camera?

is quite simple:
You need to change video capturing from file to video capturing from camera with OpenCV, like this:
`vid_capture = cv2.VideoCapture(0, cv2.CAP_DSHOW)`

and if you want see realtime pridictions, add a line of code with frame drawing in the end of `while vid_capture.isOpened()` block
`cv2.imshow('Face AntiSpoofing', frame)`

UPD:
I implemented the recognition for the video stream from the webcam and commited the changes. https://github.com/hairymax/Face-AntiSpoofing/commit/eed4e278d80e60c2c63ea8e480886266e566ec63
You can check it out =)

**Comment by danii92** [comment]
thanks Maxim
